# Generated by Django 4.0.1 on 2022-04-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_delete', 'Delete author'), ('can_update', 'Update author'), ('can_create', 'Create author'))},
        ),
    ]
